apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlflow-artifacts-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/mlflow-artifacts  # This directory will be created on your node
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-artifacts-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: mlflow-artifacts-pv
  storageClassName: ""

