services:
  db:
    image: postgres
    container_name: ${POSTGRES_DB}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  wine-quality-db-init:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: wine-quality-db-init
    depends_on:
      - db
    command: ["python", "init/init_db.py"]
    volumes:
      - .:/app
    working_dir: /app

  wine-quality-api:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: wine-quality-api
    restart: always
    ports:
      - "8000:80"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - wine-quality-db-init

volumes:
  pg_data:

