services:
  db:
    image: postgres
    container_name: wine-quality-db
    restart: always
    environment:
      POSTGRES_USER: wine123
      POSTGRES_PASSWORD: wine123
      POSTGRES_DB: wine-quality-db
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  wine-quality-db-init:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: wine-quality-db-init
    depends_on:
      - db
    command: ["python", "init/init_db.py"]
    volumes:
      - .:/app
    working_dir: /app

  wine-quality-api:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: wine-quality-api
    restart: always
    ports:
      - "8000:80"
    environment:
      - POSTGRES_USER=wine123
      - POSTGRES_PASSWORD=wine123
      - POSTGRES_DB=wine-quality-db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - wine-quality-db-init

volumes:
  pg_data:

