services:
  postgres:
    image: postgres
    container_name: wine-quality-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: wine123
      POSTGRES_PASSWORD: wine123
      POSTGRES_DB: wine-quality-db
    volumes:
      - wine_pgdata:/var/lib/postgresql/data
      - csv_data:/csv_data

volumes:
  wine_pgdata:
  csv_data:
