name: Build and Push Docker Images to Docker Hub

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/wine-quality-prediction  # Change to your DockerHub username/repo

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build and push API image
    - name: Build and push API image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./api/Dockerfile
        push: true
        tags: ${{ env.IMAGE_NAME }}-api:latest

    # Build and push training image
    - name: Build and push training image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./training/Dockerfile
        push: true
        tags: ${{ env.IMAGE_NAME }}-training:latest

    # Build and push db-init image (optional, if you use it)
    - name: Build and push db-init image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./db/Dockerfile
        push: true
        tags: ${{ env.IMAGE_NAME }}-db-init:latest

    # Build and push promotion image (optional)
    - name: Build and push promotion image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./ci/promotion/Dockerfile
        push: true
        tags: ${{ env.IMAGE_NAME }}-promotion:latest

    # Add other images as needed (mlflow, etc.)
